export const metadata = {
  title: "Finance Report",
  description: "Generated by create next app",
};

export default function ReportLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
