export const metadata = {
  title: "Loan Application",
  description: "Generated by create next app",
};

export default function LoanApplicationLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
