export const metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function FinanceLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
