// import { formTabs } from "./page";

// const ActiveForm = () => {
//   const activeForm = formTabs.find((item) => item.active);
//   if (activeForm) {
//     return activeForm.title;
//   }
//   return null;
// };

export const metadata = {
  title: "Data Entry",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
