export const metadata = {
  title: "Loans",
  description: "Generated by create next app",
};

export default function LoansLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
