import InquiryForm from "../../components/Forms/InquiryForm";
import {
  blacklistReportSchema,
  blacklistSchema,
  companySchema,
  financeSchema,
  inquirySchema,
  installementSchema,
  loanApplicationSchema,
  loanSchema,
  securityDepositSchema,
} from "./schemas";

export const inquiryFields = [
  {
    label: "User",
    name: "user",
    type: "select",
    required: true,
    defaultValue: "",
    placeholder: "Enter User ID",
  },
  {
    label: "Finance",
    name: "finance",
    type: "select",
    required: true,
    defaultValue: "",
    placeholder: "Enter Finance ID",
  },
  {
    label: "Reason",
    name: "reason",
    type: "textarea",
    required: true,
    defaultValue: "",
    maxLength: 500,
    placeholder: "Enter Reason",
  },
  {
    label: "Inquirer",
    name: "inquirer",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Inquirer User ID",
  },
];
export const loanFields = [
  {
    label: "User ID",
    name: "user",
    type: "text",
    required: true,
    defaultValue: "whjwgjg",
    placeholder: "Enter User ID",
  },
  {
    label: "Finance ID",
    name: "finance",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Finance ID",
  },
  {
    label: "Account Number",
    name: "account_number",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 20,
    placeholder: "Enter Account Number",
  },
  {
    label: "Total Loan",
    name: "total_loan",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    placeholder: "Enter Total Loan Amount",
  },
  {
    label: "Total Paid",
    name: "total_paid",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    placeholder: "Enter Total Paid Amount",
  },
  // {
  //   label: "Loan Outstanding",
  //   name: "loan_outstanding",
  //   type: "number",
  //   step: "0.01",
  //   required: true,
  //   defaultValue: 0.0,
  //   readOnly: true,
  //   placeholder: "Calculated Loan Outstanding",
  // },
  {
    label: "Loan Limit",
    name: "loan_limit",
    type: "number",
    step: "0.01",
    defaultValue: 0.0,
    placeholder: "Enter Loan Limit",
  },
  {
    label: "Interest Rate",
    name: "interest_rate",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    maxLength: 5,
    placeholder: "Enter Interest Rate",
  },
  {
    label: "Overdue Amount",
    name: "overdue_amount",
    type: "number",
    step: "0.01",
    defaultValue: 0.0,
    placeholder: "Enter Overdue Amount",
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    options: [
      { value: "good", label: "Good" },
      { value: "watchlist", label: "Watchlist" },
      { value: "pass", label: "Pass" },
      { value: "npl", label: "Npl" },
      { value: "doubtful", label: "Doubtful" },
      { value: "bad debt", label: "Bad debt" },
    ],
    required: true,
    defaultValue: "good",
  },
  {
    label: "Loan Type",
    name: "loan_type",
    type: "select",
    options: [
      { value: "term", label: "Term" },
      { value: "overdraft", label: "Overdraft" },
    ],
    required: false,
    defaultValue: "term",
  },
  {
    label: "Is Closed",
    name: "is_closed",
    type: "radio",
    required: true,
    options: [
      { label: "Yes", value: true },
      { label: "No", value: false },
    ],
  },
  {
    label: "Utilization Percent",
    name: "utilization_percent",
    type: "number",
    step: "0.01",
    defaultValue: 0.0,
    required: false,
    placeholder: "Enter Utilization Percent",
  },
];

export const companyFormFields = [
  {
    label: "Name",
    name: "name",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 255,
    placeholder: "Enter Company Name",
  },
  {
    label: "PAN Number",
    name: "pan_num",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 9,
    placeholder: "Enter PAN Number",
  },
  {
    label: "VAT Number",
    name: "vat_num",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 9,
    placeholder: "Enter VAT Number",
  },
  {
    label: "Permanent Address",
    name: "permanent_add",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 255,
    placeholder: "Enter Permanent Address",
  },
  {
    label: "PAN Registration Date",
    name: "pan_registration_date",
    type: "date",
    required: true,
    defaultValue: "",
    placeholder: "Enter PAN Registration Date",
  },
  {
    label: "PAN Registration Place",
    name: "pan_registration_place",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 100,
    placeholder: "Enter PAN Registration Place",
  },
  {
    label: "Profiter",
    name: "profiter",
    type: "number",
    required: false,
    defaultValue: "",
    placeholder: "Enter Profiter User ID",
  },
  {
    label: "Lone Taker Type",
    name: "lone_taker_type",
    type: "select",
    options: [
      { value: "personal", label: "Personal" },
      { value: "company", label: "Company" },
    ],
    required: true,
    defaultValue: "company",
  },
];

export const securityDepositFormFields = [
  {
    label: "Loan",
    name: "loan",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Loan Account ID",
  },
  {
    label: "Type",
    name: "type",
    type: "select",
    options: [
      { value: "real state", label: "Real State" },
      { value: "fixed asset", label: "Fixed Asset" },
      { value: "higher purchase", label: "Higher Purchase" },
    ],
    required: true,
    defaultValue: "real state",
  },
  {
    label: "Description",
    name: "description",
    type: "textarea",
    required: true,
    defaultValue: "",
    placeholder: "Enter Description",
  },
  {
    label: "Ownership Type",
    name: "ownership_type",
    type: "select",
    options: [
      { value: "own", label: "Own" },
      { value: "third party", label: "Third Party" },
    ],
    required: true,
    defaultValue: "own",
  },
  {
    label: "Coverage Percentage",
    name: "coverage_percentage",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: "",
    placeholder: "Enter Coverage Percentage",
  },
  {
    label: "Nature of Charge",
    name: "nature_of_charge",
    type: "text",
    required: true,
    defaultValue: "first_charge",
    readOnly: true,
  },
  {
    label: "Latest Value",
    name: "latest_value",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: "",
    placeholder: "Enter Latest Value",
  },
  {
    label: "Latest Valuation Date",
    name: "latest_valuation_date",
    type: "date",
    required: true,
    defaultValue: "",
    placeholder: "Enter Latest Valuation Date",
  },
];

const financeFormFields = [
  {
    label: "Name",
    name: "name",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 100,
    placeholder: "Enter Finance Name",
  },
  {
    label: "Parent",
    name: "parent",
    type: "number",
    required: false,
    defaultValue: "",
    placeholder: "Enter Parent Finance ID",
  },
  {
    label: "Description",
    name: "description",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 1000,
    placeholder: "Enter Description",
  },
  {
    label: "Location",
    name: "location",
    type: "json",
    required: false,
    defaultValue: {},
    placeholder: "Enter Location JSON",
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    required: false,
    defaultValue: "",
    placeholder: "Enter Email",
  },
  {
    label: "Phone Number",
    name: "phone_number",
    type: "text",
    required: true,
    defaultValue: "",
    maxLength: 15,
    placeholder: "Enter Phone Number",
  },
  {
    label: "Website URL",
    name: "website_url",
    type: "url",
    required: false,
    defaultValue: "",
    placeholder: "Enter Website URL",
  },
];

export const loanApplicationFields = [
  {
    label: "Loan Amount",
    name: "loan_amount",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    placeholder: "Enter Loan Amount",
  },
  {
    label: "Finance",
    name: "finance",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Finance ID",
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    options: [
      { value: "pending", label: "Pending" },
      { value: "approved", label: "Approved" },
      { value: "rejected", label: "Rejected" },
    ],
    required: true,
    defaultValue: "pending",
  },
  {
    name: "first_name",
    label: "First Name",
    type: "text",
    required: true,
    placeholder: "Enter First Name",
    defaultValue: "",
  },
  {
    name: "middle_name",
    label: "Middle Name",
    type: "text",
    required: false,
    placeholder: "Enter Middle Name",
    defaultValue: "",
  },
  {
    name: "last_name",
    label: "Last Name",
    type: "text",
    required: true,
    placeholder: "Enter Last Name",
    defaultValue: "",
  },
  {
    name: "citizenship_number",
    label: "Citizenship Number",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Citizenship Number",
  },
  {
    name: "citizenship_issued_place",
    label: "Citizenship Issued Place",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter CitizenShip Issued Place",
  },
  {
    name: "citizenship_issued_date",
    label: "Citizenship Issued Date",
    type: "date",
    required: true,
    defaultValue: "",
    placeholder: "Enter CitizenShip Issued Date",
  },
  // {
  //   name: "gender",
  //   label: "Gender",
  //   type: "select",
  //   required: true,
  //   options: ["male", "female"],
  // },
  // { name: "dob", label: "Date of Birth", type: "date", required: false },
  {
    name: "father_name",
    label: "Father Name",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Father Name",
  },

  {
    name: "phone_number",
    label: "Phone Number",
    type: "number",
    required: true,
    defaultValue: "",
    placeholder: "Enter Phone Number",
  },
];

export const installmentFields = [
  {
    label: "Loan",
    name: "loan",
    type: "number",
    required: true,
    defaultValue: "",
    placeholder: "Enter Loan ID",
  },
  {
    label: "Due Date",
    name: "due_date",
    type: "date",
    required: true,
    defaultValue: "",
    placeholder: "Select Due Date",
  },
  {
    label: "Paid Date",
    name: "paid_date",
    type: "date",
    required: true,
    defaultValue: "",
    placeholder: "Select Paid Date",
  },
  {
    label: "Total Due",
    name: "total_due",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    placeholder: "Enter Total Due Amount",
  },
  {
    label: "Total Paid",
    name: "total_paid",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    placeholder: "Enter Total Paid Amount",
  },
  {
    label: "Total Outstanding",
    name: "total_outstanding",
    type: "number",
    step: "0.01",
    required: true,
    defaultValue: 0.0,
    placeholder: "Enter Total Outstanding Amount",
  },
];

export const blacklistReportFields = [
  {
    label: "User",
    name: "user",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter User ID",
  },
  {
    label: "Finance",
    name: "finance",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Finance ID",
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    options: [
      { value: "progress", label: "Progress" },
      { value: "rejected", label: "Rejected" },
      { value: "approved", label: "Approved" },
    ],
    required: true,
    defaultValue: "progress",
    placeholder: "Select Status",
  },
];

export const blacklistFields = [
  {
    label: "User",
    name: "user",
    type: "number",
    required: true,
    defaultValue: "",
    placeholder: "Enter User ID",
  },
  {
    label: "Finance",
    name: "finance",
    type: "number",
    required: true,
    defaultValue: "",
    placeholder: "Enter Finance ID",
  },
  {
    label: "Category",
    name: "category",
    type: "select",
    options: [
      { value: "borrower", label: "Borrower" },
      { value: "guarantor", label: "Guarantor" },
    ],
    required: true,
    defaultValue: "borrower",
    placeholder: "Select Category",
  },
  {
    label: "Reason",
    name: "reason",
    type: "text",
    required: true,
    defaultValue: "",
    placeholder: "Enter Reason",
  },
  {
    label: "Remarks",
    name: "remarks",
    type: "textarea",
    required: false,
    defaultValue: "",
    placeholder: "Enter Remarks",
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    options: [
      { value: "blacklisted", label: "Blacklisted" },
      { value: "relished", label: "Relished" },
    ],
    required: true,
    defaultValue: "blacklisted",
    placeholder: "Select Status",
  },
  {
    label: "Release Date",
    name: "release_date",
    type: "date",
    required: false,
    defaultValue: "",
    placeholder: "Select Release Date",
  },
  {
    label: "Report Date",
    name: "report_date",
    type: "date",
    required: true,
    defaultValue: "",
    placeholder: "Select Report Date",
  },
];

export const formTabs = [
  {
    id: 1,
    title: "Inquiry",
    active: true,
    schema: inquirySchema,
    fields: inquiryFields,
    endpoint: "cooperative/inquiries",
    Component: InquiryForm,
  },
  {
    id: 2,
    title: "Loan Account",
    active: false,
    schema: loanSchema,
    fields: loanFields,
    endpoint: "cooperative/loan",
    Component: InquiryForm,
  },

  {
    id: 3,
    title: "Company Details",
    active: false,
    schema: companySchema,
    fields: companyFormFields,
    endpoint: "cooperative/companys",
    Component: InquiryForm,
  },
  {
    id: 4,
    title: "Finance",
    active: false,
    schema: financeSchema,
    fields: financeFormFields,
    endpoint: "cooperative/finance",
    Component: InquiryForm,
  },
  {
    id: 5,
    title: "Security Deposit",
    active: false,
    schema: securityDepositSchema,
    fields: securityDepositFormFields,
    endpoint: "cooperative/securitydeposits",
    Component: InquiryForm,
  },
  {
    id: 6,
    title: "Loan Application",
    active: false,
    schema: loanApplicationSchema,
    fields: loanApplicationFields,
    endpoint: "cooperative/loanapplications",
    Component: InquiryForm,
  },
  {
    id: 7,
    title: "Installment",
    active: false,
    schema: installementSchema,
    fields: installmentFields,
    endpoint: "cooperative/installments",
    Component: InquiryForm,
  },
  {
    id: 8,
    title: "Blacklist",
    active: false,
    schema: blacklistSchema,
    fields: blacklistFields,
    endpoint: "cooperative/blacklists",
    Component: InquiryForm,
  },
  {
    id: 9,
    title: "Blacklist Report",
    active: false,
    schema: blacklistReportSchema,
    fields: blacklistReportFields,
    endpoint: "cooperative/blacklistreports",
    Component: InquiryForm,
  },
];
